apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloud-cluster.fullname" . }}-telemetry-api
  labels:
    {{- include "cloud-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: telemetry-api
  {{- if .Values.telemetryApi.workloadIdentity.clientId }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.telemetryApi.workloadIdentity.clientId | quote }}
  {{- end }}
