apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-cluster.fullname" . }}-telemetry-api
  labels:
    {{- include "cloud-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: telemetry-api
spec:
  type: {{ .Values.telemetryApi.service.type }}
  ports:
    - name: http
      port: {{ .Values.telemetryApi.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "cloud-cluster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: telemetry-api
