edgeHeartbeat:
  replicaCount: 1
  image:
    repository: edge-heartbeat
    tag: "0.1.0"
    pullPolicy: IfNotPresent
  serviceBus:
    existingSecret: edge-heartbeat-servicebus
  config: |
    {
      "deviceId": "",
      "heartbeatIntervalSeconds": 5,
      "serviceBusTopic": "edge-heartbeat"
    }
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 192Mi

imageRegistry: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
