#!/usr/bin/env bash
# repo-scripts/create-rg-network.sh
# Creates a resource group and virtual network in Azure Government using az cli,
# then generates a terraform.tfvars file for the infra/ template.
#
# Usage: create-rg-network.sh [options]
#   --project-name    Project name prefix (default: tactical-arc)
#   --environment     Deployment environment (default: dev)
#   --location        Azure Government region (default: usgovarizona)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
INFRA_DIR="${REPO_ROOT}/infra"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# Defaults (aligned with infra/variables.tf)
PROJECT_NAME="tactical-arc"
ENVIRONMENT="dev"
LOCATION="usgovarizona"
VNET_ADDRESS_SPACE="10.0.0.0/16"
AKS_SUBNET_PREFIX="10.0.1.0/24"
STORAGE_SUBNET_PREFIX="10.0.2.0/24"
REGISTRY_SUBNET_PREFIX="10.0.3.0/24"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-name)  PROJECT_NAME="$2"; shift 2 ;;
    --environment)   ENVIRONMENT="$2"; shift 2 ;;
    --location)      LOCATION="$2"; shift 2 ;;
    *) log_error "Unknown option: $1"; exit 1 ;;
  esac
done

RG_NAME="${PROJECT_NAME}-${ENVIRONMENT}-rg"
VNET_NAME="${PROJECT_NAME}-${ENVIRONMENT}-vnet"
AKS_SUBNET_NAME="${PROJECT_NAME}-${ENVIRONMENT}-aks-subnet"
STORAGE_SUBNET_NAME="${PROJECT_NAME}-${ENVIRONMENT}-storage-subnet"
REGISTRY_SUBNET_NAME="${PROJECT_NAME}-${ENVIRONMENT}-registry-subnet"

echo "================================================"
echo " Tactical ARC Demo - Create RG & Network"
echo "================================================"
echo ""
log_info "Project:     ${PROJECT_NAME}"
log_info "Environment: ${ENVIRONMENT}"
log_info "Location:    ${LOCATION}"
log_info "RG Name:     ${RG_NAME}"
log_info "VNet Name:   ${VNET_NAME}"
echo ""

# Verify Azure CLI is logged in to Azure Government
log_info "Verifying Azure Government login..."
if ! az cloud show --name AzureUSGovernment &>/dev/null; then
  log_error "AzureUSGovernment cloud not available. Run: az cloud set --name AzureUSGovernment"
  exit 1
fi

CURRENT_CLOUD=$(az cloud show --query name -o tsv 2>/dev/null || true)
if [[ "${CURRENT_CLOUD}" != "AzureUSGovernment" ]]; then
  log_warn "Current cloud is '${CURRENT_CLOUD}', switching to AzureUSGovernment..."
  az cloud set --name AzureUSGovernment
fi

if ! az account show &>/dev/null 2>&1; then
  log_error "Not logged in. Run: az login --environment AzureUSGovernment"
  exit 1
fi

SUBSCRIPTION_ID=$(az account show --query id -o tsv)
SUBSCRIPTION_NAME=$(az account show --query name -o tsv)
log_info "Subscription: ${SUBSCRIPTION_NAME} (${SUBSCRIPTION_ID})"
echo ""

# Create Resource Group
log_info "Creating resource group '${RG_NAME}' in '${LOCATION}'..."
az group create \
  --name "${RG_NAME}" \
  --location "${LOCATION}" \
  --tags project="${PROJECT_NAME}" environment="${ENVIRONMENT}" managed_by=terraform cloud=azure-government \
  --output table

echo ""

# Create Virtual Network
log_info "Creating virtual network '${VNET_NAME}'..."
az network vnet create \
  --resource-group "${RG_NAME}" \
  --name "${VNET_NAME}" \
  --address-prefix "${VNET_ADDRESS_SPACE}" \
  --location "${LOCATION}" \
  --tags project="${PROJECT_NAME}" environment="${ENVIRONMENT}" managed_by=terraform cloud=azure-government \
  --output table

echo ""

# Create Subnets
log_info "Creating AKS subnet '${AKS_SUBNET_NAME}'..."
az network vnet subnet create \
  --resource-group "${RG_NAME}" \
  --vnet-name "${VNET_NAME}" \
  --name "${AKS_SUBNET_NAME}" \
  --address-prefixes "${AKS_SUBNET_PREFIX}" \
  --output table

log_info "Creating storage subnet '${STORAGE_SUBNET_NAME}'..."
az network vnet subnet create \
  --resource-group "${RG_NAME}" \
  --vnet-name "${VNET_NAME}" \
  --name "${STORAGE_SUBNET_NAME}" \
  --address-prefixes "${STORAGE_SUBNET_PREFIX}" \
  --output table

log_info "Creating registry subnet '${REGISTRY_SUBNET_NAME}'..."
az network vnet subnet create \
  --resource-group "${RG_NAME}" \
  --vnet-name "${VNET_NAME}" \
  --name "${REGISTRY_SUBNET_NAME}" \
  --address-prefixes "${REGISTRY_SUBNET_PREFIX}" \
  --output table

echo ""

# Generate terraform.tfvars
TFVARS_FILE="${INFRA_DIR}/terraform.tfvars"
log_info "Generating terraform.tfvars at ${TFVARS_FILE}..."

cat > "${TFVARS_FILE}" <<EOF
# Auto-generated by create-rg-network.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Resource group and network were pre-created via Azure CLI.

location            = "${LOCATION}"
environment         = "${ENVIRONMENT}"
project_name        = "${PROJECT_NAME}"
resource_group_name = "${RG_NAME}"

vnet_address_space     = ["${VNET_ADDRESS_SPACE}"]
aks_subnet_prefix      = "${AKS_SUBNET_PREFIX}"
storage_subnet_prefix  = "${STORAGE_SUBNET_PREFIX}"
registry_subnet_prefix = "${REGISTRY_SUBNET_PREFIX}"

tags = {
  project    = "${PROJECT_NAME}"
  managed_by = "terraform"
  cloud      = "azure-government"
}
EOF

log_info "terraform.tfvars written successfully"
echo ""

log_info "Resource group and network created successfully!"
log_info ""
log_info "Next steps:"
log_info "  1. Review tfvars:    cat infra/terraform.tfvars"
log_info "  2. Init terraform:   bash repo-scripts/terraform.sh init"
log_info "  3. Import resources: terraform -chdir=infra import azurerm_resource_group.main ${RG_NAME}"
log_info "  4. Plan & apply:     bash repo-scripts/terraform.sh plan"
