apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "remote-cluster.fullname" . }}-edge-heartbeat
  labels:
    {{- include "remote-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: edge-heartbeat
data:
  config.json: |
    {{- .Values.edgeHeartbeat.config | nindent 4 }}
